# .air.toml
[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  full_bin = "APP_ENV=dev ./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "uploads"]
  exclude_file = []
  follow_symlink = true
  dir = "."
  log = "tmp/air.log"
  stop_on_error = true

[log]
  color = true
  timestamp = true
  prefix = "[air] "
