version: "3.8"

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - .data:/var/lib/postgresql/data
    networks:
      - golang-network
    env_file:
      - .env
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web
    restart: always
    env_file:
      - .env
    ports:
      - 8082:8080
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - golang-network

networks:
  golang-network:
    external: true
